### ISSUE TITLE
Cannot scan QR code

### ISSUE THREAD

**Issue by mikoladz** [helloworld1/FreeOTPPlus#60]
Hello,

I'm trying to scan a QR code to add a new token. Immediately upon touching the "scan QR code" option the image scanner quits. Sometimes it returns to the app, sometimes it quits to the home screen. Please let me know what further details you need for investigation.

Regards,
Mikolaj Menke

**Comment by JoschaLaubach** [comment]
Hi,

same issue for me. App crashes on "Scan QR Code". I'm using FreeOTP+ on Android 8.1 if that helps.

Best regards,
Joscha

**Comment by lotth** [comment]
Same for me. Partial device logs is below.
Best regards
lotth

FATAL EXCEPTION: pool-2-thread-2
Process: org.liberty.android.freeotpplus, PID: 10774
java.lang.IllegalArgumentException: Incorrect image size
at org.fedorahosted.freeotp.util.TokenQRCodeDecoder.parseQRCode(TokenQRCodeDecoder.kt:34)
at org.fedorahosted.freeotp.ui.ScanTokenActivity.analyzeImage(ScanTokenActivity.kt:160)
at org.fedorahosted.freeotp.ui.ScanTokenActivity.access$analyzeImage(ScanTokenActivity.kt:39)
at org.fedorahosted.freeotp.ui.ScanTokenActivity$startCamera$2.analyze(ScanTokenActivity.kt:97)
at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:56)
at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by davidcstevens** [comment]
Also having this issue on Android 9.0

**Comment by yuv** [comment]
+1 on recent LineageOS 16.0 (official).  The original FreeOTP plus QR scanner works fine.

**Comment by konus1** [comment]
+1 on Android 8.1.0 - just tried to switch from working FreeOTP

**Comment by helloworld1** [comment]
I saw the crash on Google Play Store. I am not able to reproduce the issue on Emulator 7.0 to 10.0 and on my own phones. Let me make some changes there so you can test out if the crash still happens.

**Comment by helloworld1** [comment]
I pushed a commit without buffer size check. If you have crash issues, could you try this version?
If you cannot compile, you can also install this debug version. It will not overwrite the release version on your device. 
https://drive.google.com/file/d/1EB-1SFfONwmttK7AWBj1cm5SzTTy4yy-/view?usp=sharing

Please report back if it work so I can release a fix soon. Thanks!

**Comment by JoschaLaubach** [comment]
Just tested it. Debug version still crashes on Android 8.1.

**Comment by davidcstevens** [comment]
Debug version still crashes on Android 9. Thanks for working on this.

**Comment by helloworld1** [comment]
I tried another attempt to fix the buffer issue. I am doing blind fix so I rely on those who can repo to test out. Feel free to try the latest master branch or this APK:
https://drive.google.com/file/d/1gGiCcyh78lnL5QoAONgMp8zhWCNY_Lil/view?usp=sharing

**Comment by davidcstevens** [comment]
Using the latest APK linked above, the app does not crash now and the camera stays open but a QR code is never scanned. The progress wheel in the corner of the box keeps spinning. (Android 9)

Blind debugging is not fun or easy. Thanks for working on it.

**Comment by JoschaLaubach** [comment]
This was a step in the right direction. The app no longer crashes, but it also doesn't detect the QR code. It shows the camera picture, a white frame to position the QR code and a spinning "loading" circle in the bottom right corner of the frame. I used a QR code from here https://freeotp.github.io/qrcode.html for testing, but nothing happened.

**Comment by helloworld1** [comment]
Yea. I think the issue is that I assume the buffer size should be just the camera image width * height for the luminous part of YUV format. But some phones is returning the image in a different format that has way more data than width * height for luminous. That will render the scanned QR image unreadable.

**Comment by helloworld1** [comment]
Would you install a debug info version and then paste back the information shown on your screen?  Thanks!

https://drive.google.com/file/d/1qXq02J8f6cKQUOnRDw285jIkHAWlmaYF/view?usp=sharing

**Comment by davidcstevens** [comment]
Image format 35
Image width: 864
Image height: 480
Image planes: 3
Image pixel stride: 1
Image row stride: 896
Image buffer remaining: 430048

**Comment by helloworld1** [comment]
Thanks a lot!

Emmmmmm, why image width is 864 while stride is 896?????
864 * 480 is not 430048

**Comment by helloworld1** [comment]
Ok, I changed to use stride size instead of width for image width. Let's see if it works this time:

https://drive.google.com/file/d/1RcsmTKsBYoADkae2KIg6f7qQS2-JlY6Y/view?usp=sharing

**Comment by davidcstevens** [comment]
The latest debug version you just posted fixes it for me (android 9). I was able to scan and successfully add a token to the debug version of the app. Thanks for fixing it!

**Comment by JoschaLaubach** [comment]
The latest debug version also works for me on Android 8.1. Thank you!

**Comment by helloworld1** [comment]
That's great to know. Thanks a lot for testing and quick response so I can fix it fast.  I will wrap things up and release a new version soon.

**Comment by helloworld1** [comment]
I committed the fix in https://github.com/helloworld1/FreeOTPPlus/commit/848e0942bbf69dfbdca85a8e9b7b0f8ebc5ac045. Thank you all for reporting and helping fixing the issue.
